### PR TITLE
wipeAppwriteBucket() implementaion in Kotlin

### PR DESCRIPTION
**Pull request by abhishekdd**
This pull request resolves [⚡ Write a wipeAppwriteBucket() Function using Kotlin #4172](https://github.com/appwrite/appwrite/issues/4172#issue-1394474097)

Please review and let me know if anything needs to be modified.

### CODE REVIEW

**Comment by abhishekdd** [comment]
This pull request addresses [https://github.com/appwrite/appwrite/issues/4172#issue-1394474097](url) .

Screenshots from testing are below.
Initially bucket has 123 files:
image

Function - variables:
image

Function - payload:
image

Function - success response:
image

Bucket is empty after function execution:
image

Function - error response:
image

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by adityaoberai — APPROVED** [review]
LGTM 👍 
image

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
