### PR TITLE
doc - Make README up-to-date

### PR DESCRIPTION
**Pull request by Emiliaaah**
I added the Java section since I saw there's an example function for that, and for the rest just added example functions that hadn't been added to the README yet.

### CODE REVIEW

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by stnguyen90** [comment]
PR modifying similar file:

* https://github.com/open-runtimes/examples/pull/31

**Comment by Emiliaaah** [comment]
So which one did you want to merge?

**Comment by christyjacob4** [comment]
@Emiliaaah could you please resolve the merge conflict?

**Comment by Meldiron** [comment]
Hey there 👋

We noticed there is a lot of overhead with the table in the readme. We decided to solve this one and for all with a GitHub action to automatically generate those: https://github.com/open-runtimes/examples/pull/133

With that said, I am closing this PR in favour of the above one. I would love to see a PR review from you on the new poll request ♥️

**Pull request closed without merging**
