### PR TITLE
[feat] Add Example for Sending HTTP Requests with Ruby Runtime

### PR DESCRIPTION
**Pull request by sudiptog81**
Sends a HTTP request. All configurations should are received as a payload. Supported options are `method`, `url`, `body`, and `headers`. Status code, response body, and response headers are returned. No function variables are necessary.

Closes  https://github.com/appwrite/appwrite/issues/4178.

Successful Request:

image

Failed Request:

image

Invalid Payload:

image

### CODE REVIEW

**Review by PineappleIOnic — CHANGES_REQUESTED** [review]
Hey There, Thank you for this PR! However a few issues that could use resolving.

1. Please resolve the merge conflict by merging main into your branch
2. Could you return a status code and the body error instead of the entire exception? It makes error handling a lot simpler

**Comment by sudiptog81** [comment]
> Hey There, Thank you for this PR! However a few issues that could use resolving.
> 
> 1. Please resolve the merge conflict by merging main into your branch
> 2. Could you return a status code and the body error instead of the entire exception? It makes error handling a lot simpler

I believe a status code is anyways returned in case of an exception, I have extended the message object in the response to include the one from the actual HTTP response in the latest commit.

**Comment by sudiptog81** [comment]
image

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by adityaoberai — APPROVED** [review]
Tested the function and got a valid response.

LGTM 👍

**Review by PineappleIOnic — APPROVED** [review]
LGTM, gets my 🦭

**Comment by christyjacob4** [comment]
@sudiptog81  please resolve the conflicts

**Comment by sudiptog81** [comment]
> @sudiptog81 please resolve the conflicts

Resolved!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
