### PR TITLE
Add missing example checks in README

### PR DESCRIPTION
**Pull request by thinkverse**
Checked off the following missing examples in the README. 👍

- Node - Get COVID-19 Stats
- PHP - Generate Giphy GIF

### CODE REVIEW

**Review by stnguyen90 — APPROVED** [review]
@thinkverse Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by thinkverse** [comment]
@stnguyen90 I see some older examples are missing from some languages, is it OK to submit PRs for them as well? 🤔

**Comment by stnguyen90** [comment]
@thinkverse, we still have some issues still available: https://github.com/appwrite/appwrite/issues?q=is%3Aissue+is%3Aopen+open-runtimes+example+no%3Aassignee. I suggest looking at those first.

**Comment by christyjacob4** [comment]
@thinkverse please resolve the conflicts

**Comment by thinkverse** [comment]
@christyjacob4 conflict resolved. 🙂

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
