### PR TITLE
Feat 4485 add python deepgram audio summary

### PR DESCRIPTION
**Pull request by Azanul**
Closes https://github.com/appwrite/appwrite/issues/4485
success_deepgram_ss_py

### CODE REVIEW

**Comment by stnguyen90** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by christyjacob4** [comment]
@Azanul can you please resolve the conflicts?

**Comment by Azanul** [comment]
> @Azanul can you please resolve the conflicts?

Done

**Review by Meldiron — APPROVED** [review]

**Comment by Meldiron** [comment]
Thanks for the amazing PR 😇 I have tested it and all works great.
Merging the PR now 🥳

**Pull request merged**
