### PR TITLE
function to wipe-appwrite-collection

### PR DESCRIPTION
**Pull request by kritikash18**
Closes: appwrite/appwrite#4098

create_new_deployment
execute_function
success_payload

### CODE REVIEW

**Comment by Meldiron** [comment]
@kritikash18 , thanks for the PR! 🤯 Please give us some time to review it.

**Review by Meldiron — CHANGES_REQUESTED** [review]
Took a quick peek, please remove the screenshots from the commits 🙏 There are purely for the PR review process so we can trust the function executed successfully. You should include them in your PR description, but no need to include them in the repository.

**Comment by kritikash18** [comment]
@Meldiron removed the screenshots from README

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by Meldiron — APPROVED** [review]

**Comment by Meldiron** [comment]
Thanks for the amazing PR 😇 I have added small changes implement pagination and improve documentation.
Merging the PR now 🥳

**Pull request merged**
