### PR TITLE
Added getprice() function in Python

### PR DESCRIPTION
**Pull request by ShahzaibJutt**
Closes: https://github.com/appwrite/appwrite/issues/4081

### CODE REVIEW

**Comment by stnguyen90** [comment]
Closes: https://github.com/appwrite/appwrite/issues/4081

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Great PR! 🤯 We left some comments during the review, please check them out. 

After making sure this works in open runtimes, please also:

1. include a readme for this like other examples
2. rename the folder to get_price to sort of match the others

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by stnguyen90** [comment]
@ShahzaibJutt have you had a chance to address my comment?

**Comment by christyjacob4** [comment]
@ShahzaibJutt Closing this PR for now. Please feel free to re-open it when you get a chance to work on it again. 

As appreciation for your efforts, we'd like to give you some Appwrite swag. You can reach out to me on Discord to claim it.

**Pull request closed without merging**
