### PR TITLE
Add generate_invoice example for java

### PR DESCRIPTION
**Pull request by sahalsaad**
To close https://github.com/appwrite/appwrite/issues/4095

Generate pdf using [itextpdf](https://mvnrepository.com/artifact/com.itextpdf/itextpdf/5.5.13.3)

Test example

Success:
success

Failed:
failedvat

### CODE REVIEW

**Review by stnguyen90 — APPROVED** [review]
Payload in the readme isn't quite right, but I was able to figure out the right format:

```shell
curl -H "X-Internal-Challenge: secret-key" \
    -H "Content-Type: application/json" \
    -X POST http://localhost:3000/ \
    -d '{"payload": "{\"currency\": \"EUR\", \"items\": [{\"name\": \"Web development\", \"price\": 15}], \"issuer\": \"Some\nIssuer\", \"customer\": \"Some\nIssuer\", \"vat\": 21}"}' | jq
```

and generate:

```json
{
  "stdout": "",
  "response": {
    "success": true,
    "invoice": "JVBERi0xLjQKJeLjz9MKMyAwIG9iago8PC9MZW5ndGggMjY3L0ZpbHRlci9GbGF0ZURlY29kZT4+c3RyZWFtCnicnZE9T8MwEIb3+xU3liHGHz07yQaoSDABNWVADNAaCZQPmqRF/HvsNFHTkInBkn33vO99eAuCGYXfIMkwrtFQzJTCHJQyLJn37wyWIDwVjtJIWnvEEBOmvQ/Tx2gOpCQz9AcZhD1DyQlwD1u4tKFK7PuxG5BShM4ilYTX+bVA6ePvMLsp9uXH2p3ZT4g6iAeEYyTiAytRyANb1ztXpbgs81bAR2gHTKaudnXjZf9WV5Ur1j8pLh4fJonVhU0x9H+aJd7P28/QuDwgz34VSqsXewuzu6rbwNh1MPuTe8ON27us/Mpd0XQWc5JJayFoXFkeK1PrYMvmNUs7ISdOTJsp7cL67/sFb3aJJgplbmRzdHJlYW0KZW5kb2JqCjUgMCBvYmoKPDwvVHlwZS9QYWdlL01lZGlhQm94WzAgMCA1OTUgODQyXS9SZXNvdXJjZXM8PC9Gb250PDwvRjEgMSAwIFIvRjIgMiAwIFI+Pj4+L0NvbnRlbnRzIDMgMCBSL1BhcmVudCA0IDAgUj4+CmVuZG9iagoxIDAgb2JqCjw8L1R5cGUvRm9udC9TdWJ0eXBlL1R5cGUxL0Jhc2VGb250L1RpbWVzLUJvbGQvRW5jb2RpbmcvV2luQW5zaUVuY29kaW5nPj4KZW5kb2JqCjIgMCBvYmoKPDwvVHlwZS9Gb250L1N1YnR5cGUvVHlwZTEvQmFzZUZvbnQvVGltZXMtUm9tYW4vRW5jb2RpbmcvV2luQW5zaUVuY29kaW5nPj4KZW5kb2JqCjQgMCBvYmoKPDwvVHlwZS9QYWdlcy9Db3VudCAxL0tpZHNbNSAwIFJdPj4KZW5kb2JqCjYgMCBvYmoKPDwvVHlwZS9DYXRhbG9nL1BhZ2VzIDQgMCBSPj4KZW5kb2JqCjcgMCBvYmoKPDwvUHJvZHVjZXIoaVRleHSuIDUuNS4xMy4zIKkyMDAwLTIwMjIgaVRleHQgR3JvdXAgTlYgXChBR1BMLXZlcnNpb25cKSkvQ3JlYXRpb25EYXRlKEQ6MjAyMzAxMDkyMzU2NDlaKS9Nb2REYXRlKEQ6MjAyMzAxMDkyMzU2NDlaKT4+CmVuZG9iagp4cmVmCjAgOAowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDA0NzAgMDAwMDAgbiAKMDAwMDAwMDU1OSAwMDAwMCBuIAowMDAwMDAwMDE1IDAwMDAwIG4gCjAwMDAwMDA2NDkgMDAwMDAgbiAKMDAwMDAwMDM0OSAwMDAwMCBuIAowMDAwMDAwNzAwIDAwMDAwIG4gCjAwMDAwMDA3NDUgMDAwMDAgbiAKdHJhaWxlcgo8PC9TaXplIDgvUm9vdCA2IDAgUi9JbmZvIDcgMCBSL0lEIFs8OTcwYWY2ZDYxYzM1NWI1NmZmYzY3MDZmMjVhODEwZDE+PDk3MGFmNmQ2MWMzNTViNTZmZmM2NzA2ZjI1YTgxMGQxPl0+PgolaVRleHQtNS41LjEzLjMKc3RhcnR4cmVmCjg5MwolJUVPRgo="
  }
}
```

which is:

[invoice.pdf](https://github.com/open-runtimes/examples/files/10377790/invoice.pdf)

**Comment by christyjacob4** [comment]
@sahalsaad please address the comments

**Comment by sahalsaad** [comment]
Updated.

**Review by Meldiron — APPROVED** [review]

**Comment by Meldiron** [comment]
Thanks for the amazing PR 😇 I have added small changes to improve readme.
Merging the PR now 🥳

**Pull request merged**
